// https://uoj.ac/problem/748

// given n, t <= 300, we want the number of strings generated by
// inserting t pairs of 10 into S, a binary string of length n.

// Consider if a T can be generated from this
// Scan left to right, greedily match with S if possible, otherwise throw in 
// a pile that has () condition. When pile is empty and a ) was thrown, 
// we "regret" previous greedy's until a ( net is returned
// This is internal to S and can be precomputed

// dp[T progress][S progress][pile balance >= 0]

// also notice how this dp on dp does not actually care about the
// complexity of the inner dp! its all about the outer transitions

#include <bits/stdc++.h>
using namespace std;
const int MOD = 998244353;

int n, t; 
int S[305];
int back[305];
// number of strings of length [T] that satisfied [S] part of S
// and have a pile balance of [k]
int dp[305][305], ndp[305][305];

int main(){
	cin >> n >> t;
	for (int i = 1; i <= n; i++){
		char c; cin >> c;
		if (c == '1') S[i] = 0; 
		else S[i] = 1;
	}

	back[0] = -1;
	for (int i = 1; i <= n; i++){
		int track = 0;
		bool flag = 1;
		for (int j = i; j >= 1; j--){
			if (S[j]) track++;
			else track--;
			if (track > 0) {
				back[i] = j-1;
				flag = 0;
				break;
			}
		}
		if (flag) back[i] = -1;
	}

	int m = n+2*t;
	dp[0][0] = 1;
	for (int T = 1; T <= m; T++){
		memset(ndp, 0, sizeof(ndp));
		for (int s = 0; s <= n; s++){
			for (int k = 0; k <= t; k++){
				if (!dp[s][k]) continue;

				// 0 case:
				if (s < n && S[s+1] == 0) 	(ndp[s+1][k] += dp[s][k]) %= MOD;
				else if (k > 0) 			(ndp[s][k-1] += dp[s][k]) %= MOD;
				else if (k == 0 && back[s] != -1) 
											(ndp[back[s]][k] += dp[s][k]) %= MOD;

				// 1 case:
				if (s < n && S[s+1] == 1) 	(ndp[s+1][k] += dp[s][k]) %= MOD;
				else if (k < t)				(ndp[s][k+1] += dp[s][k]) %= MOD;
			}
		}
		memcpy(dp, ndp, sizeof(ndp));
	}
	cout << dp[n][0] << endl;

	return 0;
}







